-- ----------------------------
-- Table structure for TinhThanh
-- ----------------------------
DROP TABLE IF EXISTS TinhThanh;
CREATE TABLE TinhThanh (
  ID varchar(5) NOT NULL,
  Ten varchar(100) NOT NULL,
  Loai varchar(30) NOT NULL,
  PRIMARY KEY (ID)
) 

delete from TinhThanh
delete from QuanHuyen

-- ----------------------------
-- Records of TinhThanh
-- ----------------------------
INSERT INTO TinhThanh VALUES ('01', N'Hà Nội', N'Trung ương');
INSERT INTO TinhThanh VALUES ('02', N'Hà Giang', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('04', N'Cao Bằng', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('06', N'Bắc Kạn', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('08', N'Tuyên Quang', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('10', N'Lào Cai', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('11', N'Điện Biên', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('12', N'Lai Châu', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('14', N'Sơn La', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('15', N'Yên Bái', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('17', N'Hoà Bình', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('19', N'Thái Nguyên', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('20', N'Lạng Sơn', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('22', N'Quảng Ninh', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('24', N'Bắc Giang', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('25', N'Phú Thọ', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('26', N'Vĩnh Phúc', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('27', N'Bắc Ninh', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('30', N'Hải Dương', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('31', N'Hải Phòng', N'Trung ương');
INSERT INTO TinhThanh VALUES ('33', N'Hưng Yên', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('34', N'Thái Bình', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('35', N'Hà Nam', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('36', N'Nam Định', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('37', N'Ninh Bình', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('38', N'Thanh Hóa', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('40', N'Nghệ An', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('42', N'Hà Tĩnh', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('44', N'Quảng Bình', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('45', N'Quảng Trị', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('46', N'Thừa Thiên Huế', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('48', N'Đà Nẵng', N'Trung ương');
INSERT INTO TinhThanh VALUES ('49', N'Quảng Nam', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('51', N'Quảng Ngãi', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('52', N'Bình Định', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('54', N'Phú Yên', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('56', N'Khánh Hòa', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('58', N'Ninh Thuận', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('60', N'Bình Thuận', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('62', N'Kon Tum', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('64', N'Gia Lai', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('66', N'Đắk Lắk', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('67', N'Đắk Nông', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('68', N'Lâm Đồng', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('70', N'Bình Phước', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('72', N'Tây Ninh', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('74', N'Bình Dương', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('75', N'Đồng Nai', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('77', N'Bà Rịa - Vũng Tàu', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('79', N'TP Hồ Chí Minh', N'Trung ương');
INSERT INTO TinhThanh VALUES ('80', N'Long An', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('82', N'Tiền Giang', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('83', N'Bến Tre', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('84', N'Trà Vinh', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('86', N'Vĩnh Long', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('87', N'Đồng Tháp', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('89', N'An Giang', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('91', N'Kiên Giang', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('92', N'Cần Thơ', N'Trung ương');
INSERT INTO TinhThanh VALUES ('93', N'Hậu Giang', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('94', N'Sóc Trăng', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('95', N'Bạc Liêu', N'Tỉnh');
INSERT INTO TinhThanh VALUES ('96', N'Cà Mau', N'Tỉnh');





DROP TABLE IF EXISTS QuanHuyen;
CREATE TABLE QuanHuyen (
  ID varchar(5) NOT NULL,
  Ten varchar(100) NOT NULL,
  Loai varchar(30) NOT NULL,
  TinhThanh varchar(5) NOT NULL,
  PRIMARY KEY (ID)
)

-- ----------------------------
-- Records of QuanHuyen
-- ----------------------------
INSERT INTO QuanHuyen VALUES ('001', N'Quận Ba Đình', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('002', N'Quận Hoàn Kiếm', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('003', N'Quận Tây Hồ', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('004', N'Quận Long Biên', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('005', N'Quận Cầu Giấy', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('006', N'Quận Đống Đa', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('007', N'Quận Hai Bà Trưng', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('008', N'Quận Hoàng Mai', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('009', N'Quận Thanh Xuân', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('016', N'Huyện Sóc Sơn', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('017', N'Huyện Đông Anh', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('018', N'Huyện Gia Lâm', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('019', N'Quận Nam Từ Liêm', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('020', N'Huyện Thanh Trì', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('021', N'Quận Bắc Từ Liêm', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('024', N'Hà Giang', N'Thành phố', '02');
INSERT INTO QuanHuyen VALUES ('026', N'Huyện Đồng Văn', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('027', N'Huyện Mèo Vạc', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('028', N'Huyện Yên Minh', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('029', N'Huyện Quản Bạ', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('030', N'Huyện Vị Xuyên', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('031', N'Huyện Bắc Mê', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('032', N'Huyện Hoàng Su Phì', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('033', N'Huyện Xín Mần', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('034', N'Huyện Bắc Quang', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('035', N'Huyện Quang Bình', N'Huyện', '02');
INSERT INTO QuanHuyen VALUES ('040', N'Cao Bằng', N'Thành phố', '04');
INSERT INTO QuanHuyen VALUES ('042', N'Huyện Bảo Lâm', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('043', N'Huyện Bảo Lạc', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('044', N'Huyện Thông Nông', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('045', N'Huyện Hà Quảng', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('046', N'Huyện Trà Lĩnh', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('047', N'Huyện Trùng Khánh', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('048', N'Huyện Hạ Lang', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('049', N'Huyện Quảng Uyên', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('050', N'Huyện Phục Hoà', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('051', N'Huyện Hoà An', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('052', N'Huyện Nguyên Bình', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('053', N'Huyện Thạch An', N'Huyện', '04');
INSERT INTO QuanHuyen VALUES ('058', N'Bắc Kạn', N'Thành phố', '06');
INSERT INTO QuanHuyen VALUES ('060', N'Huyện Pác Nặm', N'Huyện', '06');
INSERT INTO QuanHuyen VALUES ('061', N'Huyện Ba Bể', N'Huyện', '06');
INSERT INTO QuanHuyen VALUES ('062', N'Huyện Ngân Sơn', N'Huyện', '06');
INSERT INTO QuanHuyen VALUES ('063', N'Huyện Bạch Thông', N'Huyện', '06');
INSERT INTO QuanHuyen VALUES ('064', N'Huyện Chợ Đồn', N'Huyện', '06');
INSERT INTO QuanHuyen VALUES ('065', N'Huyện Chợ Mới', N'Huyện', '06');
INSERT INTO QuanHuyen VALUES ('066', N'Huyện Na Rì', N'Huyện', '06');
INSERT INTO QuanHuyen VALUES ('070', N'Tuyên Quang', N'Thành phố', '08');
INSERT INTO QuanHuyen VALUES ('071', N'Huyện Lâm Bình', N'Huyện', '08');
INSERT INTO QuanHuyen VALUES ('072', N'Huyện Nà Hang', N'Huyện', '08');
INSERT INTO QuanHuyen VALUES ('073', N'Huyện Chiêm Hóa', N'Huyện', '08');
INSERT INTO QuanHuyen VALUES ('074', N'Huyện Hàm Yên', N'Huyện', '08');
INSERT INTO QuanHuyen VALUES ('075', N'Huyện Yên Sơn', N'Huyện', '08');
INSERT INTO QuanHuyen VALUES ('076', N'Huyện Sơn Dương', N'Huyện', '08');
INSERT INTO QuanHuyen VALUES ('080', N'Lào Cai', N'Thành phố', '10');
INSERT INTO QuanHuyen VALUES ('082', N'Huyện Bát Xát', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('083', N'Huyện Mường Khương', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('084', N'Huyện Si Ma Cai', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('085', N'Huyện Bắc Hà', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('086', N'Huyện Bảo Thắng', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('087', N'Huyện Bảo Yên', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('088', N'Huyện Sa Pa', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('089', N'Huyện Văn Bàn', N'Huyện', '10');
INSERT INTO QuanHuyen VALUES ('094', N'Điện Biên Phủ', N'Thành phố', '11');
INSERT INTO QuanHuyen VALUES ('095', N'Thị Xã Mường Lay', N'Thị xã', '11');
INSERT INTO QuanHuyen VALUES ('096', N'Huyện Mường Nhé', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('097', N'Huyện Mường Chà', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('098', N'Huyện Tủa Chùa', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('099', N'Huyện Tuần Giáo', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('100', N'Huyện Điện Biên', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('101', N'Huyện Điện Biên Đông', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('102', N'Huyện Mường Ảng', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('103', N'Huyện Nậm Pồ', N'Huyện', '11');
INSERT INTO QuanHuyen VALUES ('105', N'Lai Châu', N'Thành phố', '12');
INSERT INTO QuanHuyen VALUES ('106', N'Huyện Tam Đường', N'Huyện', '12');
INSERT INTO QuanHuyen VALUES ('107', N'Huyện Mường Tè', N'Huyện', '12');
INSERT INTO QuanHuyen VALUES ('108', N'Huyện Sìn Hồ', N'Huyện', '12');
INSERT INTO QuanHuyen VALUES ('109', N'Huyện Phong Thổ', N'Huyện', '12');
INSERT INTO QuanHuyen VALUES ('110', N'Huyện Than Uyên', N'Huyện', '12');
INSERT INTO QuanHuyen VALUES ('111', N'Huyện Tân Uyên', N'Huyện', '12');
INSERT INTO QuanHuyen VALUES ('112', N'Huyện Nậm Nhùn', N'Huyện', '12');
INSERT INTO QuanHuyen VALUES ('116', N'Sơn La', N'Thành phố', '14');
INSERT INTO QuanHuyen VALUES ('118', N'Huyện Quỳnh Nhai', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('119', N'Huyện Thuận Châu', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('120', N'Huyện Mường La', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('121', N'Huyện Bắc Yên', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('122', N'Huyện Phù Yên', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('123', N'Huyện Mộc Châu', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('124', N'Huyện Yên Châu', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('125', N'Huyện Mai Sơn', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('126', N'Huyện Sông Mã', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('127', N'Huyện Sốp Cộp', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('128', N'Huyện Vân Hồ', N'Huyện', '14');
INSERT INTO QuanHuyen VALUES ('132', N'Yên Bái', N'Thành phố', '15');
INSERT INTO QuanHuyen VALUES ('133', N'Thị xã Nghĩa Lộ', N'Thị xã', '15');
INSERT INTO QuanHuyen VALUES ('135', N'Huyện Lục Yên', N'Huyện', '15');
INSERT INTO QuanHuyen VALUES ('136', N'Huyện Văn Yên', N'Huyện', '15');
INSERT INTO QuanHuyen VALUES ('137', N'Huyện Mù Căng Chải', N'Huyện', '15');
INSERT INTO QuanHuyen VALUES ('138', N'Huyện Trấn Yên', N'Huyện', '15');
INSERT INTO QuanHuyen VALUES ('139', N'Huyện Trạm Tấu', N'Huyện', '15');
INSERT INTO QuanHuyen VALUES ('140', N'Huyện Văn Chấn', N'Huyện', '15');
INSERT INTO QuanHuyen VALUES ('141', N'Huyện Yên Bình', N'Huyện', '15');
INSERT INTO QuanHuyen VALUES ('148', N'Hòa Bình', N'Thành phố', '17');
INSERT INTO QuanHuyen VALUES ('150', N'Huyện Đà Bắc', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('151', N'Huyện Kỳ Sơn', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('152', N'Huyện Lương Sơn', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('153', N'Huyện Kim Bôi', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('154', N'Huyện Cao Phong', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('155', N'Huyện Tân Lạc', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('156', N'Huyện Mai Châu', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('157', N'Huyện Lạc Sơn', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('158', N'Huyện Yên Thủy', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('159', N'Huyện Lạc Thủy', N'Huyện', '17');
INSERT INTO QuanHuyen VALUES ('164', N'Thái Nguyên', N'Thành phố', '19');
INSERT INTO QuanHuyen VALUES ('165', N'Sông Công', N'Thành phố', '19');
INSERT INTO QuanHuyen VALUES ('167', N'Huyện Định Hóa', N'Huyện', '19');
INSERT INTO QuanHuyen VALUES ('168', N'Huyện Phú Lương', N'Huyện', '19');
INSERT INTO QuanHuyen VALUES ('169', N'Huyện Đồng Hỷ', N'Huyện', '19');
INSERT INTO QuanHuyen VALUES ('170', N'Huyện Võ Nhai', N'Huyện', '19');
INSERT INTO QuanHuyen VALUES ('171', N'Huyện Đại Từ', N'Huyện', '19');
INSERT INTO QuanHuyen VALUES ('172', N'Thị xã Phổ Yên', N'Thị xã', '19');
INSERT INTO QuanHuyen VALUES ('173', N'Huyện Phú Bình', N'Huyện', '19');
INSERT INTO QuanHuyen VALUES ('178', N'Lạng Sơn', N'Thành phố', '20');
INSERT INTO QuanHuyen VALUES ('180', N'Huyện Tràng Định', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('181', N'Huyện Bình Gia', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('182', N'Huyện Văn Lãng', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('183', N'Huyện Cao Lộc', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('184', N'Huyện Văn Quan', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('185', N'Huyện Bắc Sơn', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('186', N'Huyện Hữu Lũng', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('187', N'Huyện Chi Lăng', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('188', N'Huyện Lộc Bình', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('189', N'Huyện Đình Lập', N'Huyện', '20');
INSERT INTO QuanHuyen VALUES ('193', N'Hạ Long', N'Thành phố', '22');
INSERT INTO QuanHuyen VALUES ('194', N'Móng Cái', N'Thành phố', '22');
INSERT INTO QuanHuyen VALUES ('195', N'Cẩm Phả', N'Thành phố', '22');
INSERT INTO QuanHuyen VALUES ('196', N'Uông Bí', N'Thành phố', '22');
INSERT INTO QuanHuyen VALUES ('198', N'Huyện Bình Liêu', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('199', N'Huyện Tiên Yên', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('200', N'Huyện Đầm Hà', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('201', N'Huyện Hải Hà', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('202', N'Huyện Ba Chẽ', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('203', N'Huyện Vân Đồn', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('204', N'Huyện Hoành Bồ', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('205', N'Thị xã Đông Triều', N'Thị xã', '22');
INSERT INTO QuanHuyen VALUES ('206', N'Thị xã Quảng Yên', N'Thị xã', '22');
INSERT INTO QuanHuyen VALUES ('207', N'Huyện Cô Tô', N'Huyện', '22');
INSERT INTO QuanHuyen VALUES ('213', N'Bắc Giang', N'Thành phố', '24');
INSERT INTO QuanHuyen VALUES ('215', N'Huyện Yên Thế', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('216', N'Huyện Tân Yên', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('217', N'Huyện Lạng Giang', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('218', N'Huyện Lục Nam', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('219', N'Huyện Lục Ngạn', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('220', N'Huyện Sơn Động', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('221', N'Huyện Yên Dũng', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('222', N'Huyện Việt Yên', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('223', N'Huyện Hiệp Hòa', N'Huyện', '24');
INSERT INTO QuanHuyen VALUES ('227', N'Việt Trì', N'Thành phố', '25');
INSERT INTO QuanHuyen VALUES ('228', N'Thị xã Phú Thọ', N'Thị xã', '25');
INSERT INTO QuanHuyen VALUES ('230', N'Huyện Đoan Hùng', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('231', N'Huyện Hạ Hoà', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('232', N'Huyện Thanh Ba', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('233', N'Huyện Phù Ninh', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('234', N'Huyện Yên Lập', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('235', N'Huyện Cẩm Khê', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('236', N'Huyện Tam Nông', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('237', N'Huyện Lâm Thao', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('238', N'Huyện Thanh Sơn', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('239', N'Huyện Thanh Thuỷ', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('240', N'Huyện Tân Sơn', N'Huyện', '25');
INSERT INTO QuanHuyen VALUES ('243', N'Vĩnh Yên', N'Thành phố', '26');
INSERT INTO QuanHuyen VALUES ('244', N'Thị xã Phúc Yên', N'Thị xã', '26');
INSERT INTO QuanHuyen VALUES ('246', N'Huyện Lập Thạch', N'Huyện', '26');
INSERT INTO QuanHuyen VALUES ('247', N'Huyện Tam Dương', N'Huyện', '26');
INSERT INTO QuanHuyen VALUES ('248', N'Huyện Tam Đảo', N'Huyện', '26');
INSERT INTO QuanHuyen VALUES ('249', N'Huyện Bình Xuyên', N'Huyện', '26');
INSERT INTO QuanHuyen VALUES ('250', N'Huyện Mê Linh', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('251', N'Huyện Yên Lạc', N'Huyện', '26');
INSERT INTO QuanHuyen VALUES ('252', N'Huyện Vĩnh Tường', N'Huyện', '26');
INSERT INTO QuanHuyen VALUES ('253', N'Huyện Sông Lô', N'Huyện', '26');
INSERT INTO QuanHuyen VALUES ('256', N'Bắc Ninh', N'Thành phố', '27');
INSERT INTO QuanHuyen VALUES ('258', N'Huyện Yên Phong', N'Huyện', '27');
INSERT INTO QuanHuyen VALUES ('259', N'Huyện Quế Võ', N'Huyện', '27');
INSERT INTO QuanHuyen VALUES ('260', N'Huyện Tiên Du', N'Huyện', '27');
INSERT INTO QuanHuyen VALUES ('261', N'Thị xã Từ Sơn', N'Thị xã', '27');
INSERT INTO QuanHuyen VALUES ('262', N'Huyện Thuận Thành', N'Huyện', '27');
INSERT INTO QuanHuyen VALUES ('263', N'Huyện Gia Bình', N'Huyện', '27');
INSERT INTO QuanHuyen VALUES ('264', N'Huyện Lương Tài', N'Huyện', '27');
INSERT INTO QuanHuyen VALUES ('268', N'Quận Hà Đông', N'Quận', '01');
INSERT INTO QuanHuyen VALUES ('269', N'Thị xã Sơn Tây', N'Thị xã', '01');
INSERT INTO QuanHuyen VALUES ('271', N'Huyện Ba Vì', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('272', N'Huyện Phúc Thọ', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('273', N'Huyện Đan Phượng', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('274', N'Huyện Hoài Đức', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('275', N'Huyện Quốc Oai', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('276', N'Huyện Thạch Thất', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('277', N'Huyện Chương Mỹ', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('278', N'Huyện Thanh Oai', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('279', N'Huyện Thường Tín', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('280', N'Huyện Phú Xuyên', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('281', N'Huyện Ứng Hòa', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('282', N'Huyện Mỹ Đức', N'Huyện', '01');
INSERT INTO QuanHuyen VALUES ('288', N'Hải Dương', N'Thành phố', '30');
INSERT INTO QuanHuyen VALUES ('290', N'Thị xã Chí Linh', N'Thị xã', '30');
INSERT INTO QuanHuyen VALUES ('291', N'Huyện Nam Sách', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('292', N'Huyện Kinh Môn', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('293', N'Huyện Kim Thành', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('294', N'Huyện Thanh Hà', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('295', N'Huyện Cẩm Giàng', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('296', N'Huyện Bình Giang', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('297', N'Huyện Gia Lộc', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('298', N'Huyện Tứ Kỳ', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('299', N'Huyện Ninh Giang', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('300', N'Huyện Thanh Miện', N'Huyện', '30');
INSERT INTO QuanHuyen VALUES ('303', N'Quận Hồng Bàng', N'Quận', '31');
INSERT INTO QuanHuyen VALUES ('304', N'Quận Ngô Quyền', N'Quận', '31');
INSERT INTO QuanHuyen VALUES ('305', N'Quận Lê Chân', N'Quận', '31');
INSERT INTO QuanHuyen VALUES ('306', N'Quận Hải An', N'Quận', '31');
INSERT INTO QuanHuyen VALUES ('307', N'Quận Kiến An', N'Quận', '31');
INSERT INTO QuanHuyen VALUES ('308', N'Quận Đồ Sơn', N'Quận', '31');
INSERT INTO QuanHuyen VALUES ('309', N'Quận Dương Kinh', N'Quận', '31');
INSERT INTO QuanHuyen VALUES ('311', N'Huyện Thuỷ Nguyên', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('312', N'Huyện An Dương', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('313', N'Huyện An Lão', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('314', N'Huyện Kiến Thuỵ', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('315', N'Huyện Tiên Lãng', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('316', N'Huyện Vĩnh Bảo', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('317', N'Huyện Cát Hải', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('318', N'Huyện Bạch Long Vĩ', N'Huyện', '31');
INSERT INTO QuanHuyen VALUES ('323', N'Hưng Yên', N'Thành phố', '33');
INSERT INTO QuanHuyen VALUES ('325', N'Huyện Văn Lâm', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('326', N'Huyện Văn Giang', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('327', N'Huyện Yên Mỹ', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('328', N'Huyện Mỹ Hào', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('329', N'Huyện Ân Thi', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('330', N'Huyện Khoái Châu', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('331', N'Huyện Kim Động', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('332', N'Huyện Tiên Lữ', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('333', N'Huyện Phù Cừ', N'Huyện', '33');
INSERT INTO QuanHuyen VALUES ('336', N'Thái Bình', N'Thành phố', '34');
INSERT INTO QuanHuyen VALUES ('338', N'Huyện Quỳnh Phụ', N'Huyện', '34');
INSERT INTO QuanHuyen VALUES ('339', N'Huyện Hưng Hà', N'Huyện', '34');
INSERT INTO QuanHuyen VALUES ('340', N'Huyện Đông Hưng', N'Huyện', '34');
INSERT INTO QuanHuyen VALUES ('341', N'Huyện Thái Thụy', N'Huyện', '34');
INSERT INTO QuanHuyen VALUES ('342', N'Huyện Tiền Hải', N'Huyện', '34');
INSERT INTO QuanHuyen VALUES ('343', N'Huyện Kiến Xương', N'Huyện', '34');
INSERT INTO QuanHuyen VALUES ('344', N'Huyện Vũ Thư', N'Huyện', '34');
INSERT INTO QuanHuyen VALUES ('347', N'Phủ Lý', N'Thành phố', '35');
INSERT INTO QuanHuyen VALUES ('349', N'Huyện Duy Tiên', N'Huyện', '35');
INSERT INTO QuanHuyen VALUES ('350', N'Huyện Kim Bảng', N'Huyện', '35');
INSERT INTO QuanHuyen VALUES ('351', N'Huyện Thanh Liêm', N'Huyện', '35');
INSERT INTO QuanHuyen VALUES ('352', N'Huyện Bình Lục', N'Huyện', '35');
INSERT INTO QuanHuyen VALUES ('353', N'Huyện Lý Nhân', N'Huyện', '35');
INSERT INTO QuanHuyen VALUES ('356', N'Nam Định', N'Thành phố', '36');
INSERT INTO QuanHuyen VALUES ('358', N'Huyện Mỹ Lộc', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('359', N'Huyện Vụ Bản', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('360', N'Huyện Ý Yên', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('361', N'Huyện Nghĩa Hưng', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('362', N'Huyện Nam Trực', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('363', N'Huyện Trực Ninh', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('364', N'Huyện Xuân Trường', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('365', N'Huyện Giao Thủy', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('366', N'Huyện Hải Hậu', N'Huyện', '36');
INSERT INTO QuanHuyen VALUES ('369', N'Ninh Bình', N'Thành phố', '37');
INSERT INTO QuanHuyen VALUES ('370', N'Tam Điệp', N'Thành phố', '37');
INSERT INTO QuanHuyen VALUES ('372', N'Huyện Nho Quan', N'Huyện', '37');
INSERT INTO QuanHuyen VALUES ('373', N'Huyện Gia Viễn', N'Huyện', '37');
INSERT INTO QuanHuyen VALUES ('374', N'Huyện Hoa Lư', N'Huyện', '37');
INSERT INTO QuanHuyen VALUES ('375', N'Huyện Yên Khánh', N'Huyện', '37');
INSERT INTO QuanHuyen VALUES ('376', N'Huyện Kim Sơn', N'Huyện', '37');
INSERT INTO QuanHuyen VALUES ('377', N'Huyện Yên Mô', N'Huyện', '37');
INSERT INTO QuanHuyen VALUES ('380', N'Thanh Hóa', N'Thành phố', '38');
INSERT INTO QuanHuyen VALUES ('381', N'Thị xã Bỉm Sơn', N'Thị xã', '38');
INSERT INTO QuanHuyen VALUES ('382', N'Thị xã Sầm Sơn', N'Thị xã', '38');
INSERT INTO QuanHuyen VALUES ('384', N'Huyện Mường Lát', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('385', N'Huyện Quan Hóa', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('386', N'Huyện Bá Thước', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('387', N'Huyện Quan Sơn', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('388', N'Huyện Lang Chánh', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('389', N'Huyện Ngọc Lặc', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('390', N'Huyện Cẩm Thủy', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('391', N'Huyện Thạch Thành', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('392', N'Huyện Hà Trung', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('393', N'Huyện Vĩnh Lộc', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('394', N'Huyện Yên Định', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('395', N'Huyện Thọ Xuân', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('396', N'Huyện Thường Xuân', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('397', N'Huyện Triệu Sơn', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('398', N'Huyện Thiệu Hóa', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('399', N'Huyện Hoằng Hóa', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('400', N'Huyện Hậu Lộc', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('401', N'Huyện Nga Sơn', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('402', N'Huyện Như Xuân', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('403', N'Huyện Như Thanh', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('404', N'Huyện Nông Cống', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('405', N'Huyện Đông Sơn', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('406', N'Huyện Quảng Xương', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('407', N'Huyện Tĩnh Gia', N'Huyện', '38');
INSERT INTO QuanHuyen VALUES ('412', N'Vinh', N'Thành phố', '40');
INSERT INTO QuanHuyen VALUES ('413', N'Thị xã Cửa Lò', N'Thị xã', '40');
INSERT INTO QuanHuyen VALUES ('414', N'Thị xã Thái Hoà', N'Thị xã', '40');
INSERT INTO QuanHuyen VALUES ('415', N'Huyện Quế Phong', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('416', N'Huyện Quỳ Châu', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('417', N'Huyện Kỳ Sơn', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('418', N'Huyện Tương Dương', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('419', N'Huyện Nghĩa Đàn', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('420', N'Huyện Quỳ Hợp', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('421', N'Huyện Quỳnh Lưu', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('422', N'Huyện Con Cuông', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('423', N'Huyện Tân Kỳ', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('424', N'Huyện Anh Sơn', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('425', N'Huyện Diễn Châu', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('426', N'Huyện Yên Thành', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('427', N'Huyện Đô Lương', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('428', N'Huyện Thanh Chương', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('429', N'Huyện Nghi Lộc', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('430', N'Huyện Nam Đàn', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('431', N'Huyện Hưng Nguyên', N'Huyện', '40');
INSERT INTO QuanHuyen VALUES ('432', N'Thị xã Hoàng Mai', N'Thị xã', '40');
INSERT INTO QuanHuyen VALUES ('436', N'Hà Tĩnh', N'Thành phố', '42');
INSERT INTO QuanHuyen VALUES ('437', N'Thị xã Hồng Lĩnh', N'Thị xã', '42');
INSERT INTO QuanHuyen VALUES ('439', N'Huyện Hương Sơn', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('440', N'Huyện Đức Thọ', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('441', N'Huyện Vũ Quang', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('442', N'Huyện Nghi Xuân', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('443', N'Huyện Can Lộc', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('444', N'Huyện Hương Khê', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('445', N'Huyện Thạch Hà', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('446', N'Huyện Cẩm Xuyên', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('447', N'Huyện Kỳ Anh', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('448', N'Huyện Lộc Hà', N'Huyện', '42');
INSERT INTO QuanHuyen VALUES ('449', N'Thị xã Kỳ Anh', N'Thị xã', '42');
INSERT INTO QuanHuyen VALUES ('450', N'Đồng Hới', N'Thành phố', '44');
INSERT INTO QuanHuyen VALUES ('452', N'Huyện Minh Hóa', N'Huyện', '44');
INSERT INTO QuanHuyen VALUES ('453', N'Huyện Tuyên Hóa', N'Huyện', '44');
INSERT INTO QuanHuyen VALUES ('454', N'Huyện Quảng Trạch', N'Thị xã', '44');
INSERT INTO QuanHuyen VALUES ('455', N'Huyện Bố Trạch', N'Huyện', '44');
INSERT INTO QuanHuyen VALUES ('456', N'Huyện Quảng Ninh', N'Huyện', '44');
INSERT INTO QuanHuyen VALUES ('457', N'Huyện Lệ Thủy', N'Huyện', '44');
INSERT INTO QuanHuyen VALUES ('458', N'Thị xã Ba Đồn', N'Huyện', '44');
INSERT INTO QuanHuyen VALUES ('461', N'Đông Hà', N'Thành phố', '45');
INSERT INTO QuanHuyen VALUES ('462', N'Thị xã Quảng Trị', N'Thị xã', '45');
INSERT INTO QuanHuyen VALUES ('464', N'Huyện Vĩnh Linh', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('465', N'Huyện Hướng Hóa', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('466', N'Huyện Gio Linh', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('467', N'Huyện Đa Krông', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('468', N'Huyện Cam Lộ', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('469', N'Huyện Triệu Phong', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('470', N'Huyện Hải Lăng', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('471', N'Huyện Cồn Cỏ', N'Huyện', '45');
INSERT INTO QuanHuyen VALUES ('474', N'Huế', N'Thành phố', '46');
INSERT INTO QuanHuyen VALUES ('476', N'Huyện Phong Điền', N'Huyện', '46');
INSERT INTO QuanHuyen VALUES ('477', N'Huyện Quảng Điền', N'Huyện', '46');
INSERT INTO QuanHuyen VALUES ('478', N'Huyện Phú Vang', N'Huyện', '46');
INSERT INTO QuanHuyen VALUES ('479', N'Thị xã Hương Thủy', N'Thị xã', '46');
INSERT INTO QuanHuyen VALUES ('480', N'Thị xã Hương Trà', N'Thị xã', '46');
INSERT INTO QuanHuyen VALUES ('481', N'Huyện A Lưới', N'Huyện', '46');
INSERT INTO QuanHuyen VALUES ('482', N'Huyện Phú Lộc', N'Huyện', '46');
INSERT INTO QuanHuyen VALUES ('483', N'Huyện Nam Đông', N'Huyện', '46');
INSERT INTO QuanHuyen VALUES ('490', N'Quận Liên Chiểu', N'Quận', '48');
INSERT INTO QuanHuyen VALUES ('491', N'Quận Thanh Khê', N'Quận', '48');
INSERT INTO QuanHuyen VALUES ('492', N'Quận Hải Châu', N'Quận', '48');
INSERT INTO QuanHuyen VALUES ('493', N'Quận Sơn Trà', N'Quận', '48');
INSERT INTO QuanHuyen VALUES ('494', N'Quận Ngũ Hành Sơn', N'Quận', '48');
INSERT INTO QuanHuyen VALUES ('495', N'Quận Cẩm Lệ', N'Quận', '48');
INSERT INTO QuanHuyen VALUES ('497', N'Huyện Hòa Vang', N'Huyện', '48');
INSERT INTO QuanHuyen VALUES ('498', N'Huyện Hoàng Sa', N'Huyện', '48');
INSERT INTO QuanHuyen VALUES ('502', N'Tam Kỳ', N'Thành phố', '49');
INSERT INTO QuanHuyen VALUES ('503', N'Hội An', N'Thành phố', '49');
INSERT INTO QuanHuyen VALUES ('504', N'Huyện Tây Giang', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('505', N'Huyện Đông Giang', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('506', N'Huyện Đại Lộc', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('507', N'Thị xã Điện Bàn', N'Thị xã', '49');
INSERT INTO QuanHuyen VALUES ('508', N'Huyện Duy Xuyên', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('509', N'Huyện Quế Sơn', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('510', N'Huyện Nam Giang', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('511', N'Huyện Phước Sơn', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('512', N'Huyện Hiệp Đức', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('513', N'Huyện Thăng Bình', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('514', N'Huyện Tiên Phước', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('515', N'Huyện Bắc Trà My', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('516', N'Huyện Nam Trà My', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('517', N'Huyện Núi Thành', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('518', N'Huyện Phú Ninh', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('519', N'Huyện Nông Sơn', N'Huyện', '49');
INSERT INTO QuanHuyen VALUES ('522', N'Quảng Ngãi', N'Thành phố', '51');
INSERT INTO QuanHuyen VALUES ('524', N'Huyện Bình Sơn', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('525', N'Huyện Trà Bồng', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('526', N'Huyện Tây Trà', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('527', N'Huyện Sơn Tịnh', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('528', N'Huyện Tư Nghĩa', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('529', N'Huyện Sơn Hà', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('530', N'Huyện Sơn Tây', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('531', N'Huyện Minh Long', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('532', N'Huyện Nghĩa Hành', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('533', N'Huyện Mộ Đức', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('534', N'Huyện Đức Phổ', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('535', N'Huyện Ba Tơ', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('536', N'Huyện Lý Sơn', N'Huyện', '51');
INSERT INTO QuanHuyen VALUES ('540', N'Qui Nhơn', N'Thành phố', '52');
INSERT INTO QuanHuyen VALUES ('542', N'Huyện An Lão', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('543', N'Huyện Hoài Nhơn', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('544', N'Huyện Hoài Ân', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('545', N'Huyện Phù Mỹ', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('546', N'Huyện Vĩnh Thạnh', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('547', N'Huyện Tây Sơn', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('548', N'Huyện Phù Cát', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('549', N'Thị xã An Nhơn', N'Thị xã', '52');
INSERT INTO QuanHuyen VALUES ('550', N'Huyện Tuy Phước', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('551', N'Huyện Vân Canh', N'Huyện', '52');
INSERT INTO QuanHuyen VALUES ('555', N'Tuy Hoà', N'Thành phố', '54');
INSERT INTO QuanHuyen VALUES ('557', N'Thị xã Sông Cầu', N'Thị xã', '54');
INSERT INTO QuanHuyen VALUES ('558', N'Huyện Đồng Xuân', N'Huyện', '54');
INSERT INTO QuanHuyen VALUES ('559', N'Huyện Tuy An', N'Huyện', '54');
INSERT INTO QuanHuyen VALUES ('560', N'Huyện Sơn Hòa', N'Huyện', '54');
INSERT INTO QuanHuyen VALUES ('561', N'Huyện Sông Hinh', N'Huyện', '54');
INSERT INTO QuanHuyen VALUES ('562', N'Huyện Tây Hoà', N'Huyện', '54');
INSERT INTO QuanHuyen VALUES ('563', N'Huyện Phú Hoà', N'Huyện', '54');
INSERT INTO QuanHuyen VALUES ('564', N'Huyện Đông Hòa', N'Huyện', '54');
INSERT INTO QuanHuyen VALUES ('568', N'Nha Trang', N'Thành phố', '56');
INSERT INTO QuanHuyen VALUES ('569', N'Cam Ranh', N'Thành phố', '56');
INSERT INTO QuanHuyen VALUES ('570', N'Huyện Cam Lâm', N'Huyện', '56');
INSERT INTO QuanHuyen VALUES ('571', N'Huyện Vạn Ninh', N'Huyện', '56');
INSERT INTO QuanHuyen VALUES ('572', N'Thị xã Ninh Hòa', N'Thị xã', '56');
INSERT INTO QuanHuyen VALUES ('573', N'Huyện Khánh Vĩnh', N'Huyện', '56');
INSERT INTO QuanHuyen VALUES ('574', N'Huyện Diên Khánh', N'Huyện', '56');
INSERT INTO QuanHuyen VALUES ('575', N'Huyện Khánh Sơn', N'Huyện', '56');
INSERT INTO QuanHuyen VALUES ('576', N'Huyện Trường Sa', N'Huyện', '56');
INSERT INTO QuanHuyen VALUES ('582', N'Phan Rang-Tháp Chàm', N'Thành phố', '58');
INSERT INTO QuanHuyen VALUES ('584', N'Huyện Bác Ái', N'Huyện', '58');
INSERT INTO QuanHuyen VALUES ('585', N'Huyện Ninh Sơn', N'Huyện', '58');
INSERT INTO QuanHuyen VALUES ('586', N'Huyện Ninh Hải', N'Huyện', '58');
INSERT INTO QuanHuyen VALUES ('587', N'Huyện Ninh Phước', N'Huyện', '58');
INSERT INTO QuanHuyen VALUES ('588', N'Huyện Thuận Bắc', N'Huyện', '58');
INSERT INTO QuanHuyen VALUES ('589', N'Huyện Thuận Nam', N'Huyện', '58');
INSERT INTO QuanHuyen VALUES ('593', N'Phan Thiết', N'Thành phố', '60');
INSERT INTO QuanHuyen VALUES ('594', N'Thị xã La Gi', N'Thị xã', '60');
INSERT INTO QuanHuyen VALUES ('595', N'Huyện Tuy Phong', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('596', N'Huyện Bắc Bình', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('597', N'Huyện Hàm Thuận Bắc', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('598', N'Huyện Hàm Thuận Nam', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('599', N'Huyện Tánh Linh', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('600', N'Huyện Đức Linh', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('601', N'Huyện Hàm Tân', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('602', N'Huyện Phú Quí', N'Huyện', '60');
INSERT INTO QuanHuyen VALUES ('608', N'Kon Tum', N'Thành phố', '62');
INSERT INTO QuanHuyen VALUES ('610', N'Huyện Đắk Glei', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('611', N'Huyện Ngọc Hồi', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('612', N'Huyện Đắk Tô', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('613', N'Huyện Kon Plông', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('614', N'Huyện Kon Rẫy', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('615', N'Huyện Đắk Hà', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('616', N'Huyện Sa Thầy', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('617', N'Huyện Tu Mơ Rông', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('618', N'Huyện Ia H Drai', N'Huyện', '62');
INSERT INTO QuanHuyen VALUES ('622', N'Pleiku', N'Thành phố', '64');
INSERT INTO QuanHuyen VALUES ('623', N'Thị xã An Khê', N'Thị xã', '64');
INSERT INTO QuanHuyen VALUES ('624', N'Thị xã Ayun Pa', N'Thị xã', '64');
INSERT INTO QuanHuyen VALUES ('625', N'Huyện KBang', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('626', N'Huyện Đăk Đoa', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('627', N'Huyện Chư Păh', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('628', N'Huyện Ia Grai', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('629', N'Huyện Mang Yang', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('630', N'Huyện Kông Chro', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('631', N'Huyện Đức Cơ', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('632', N'Huyện Chư Prông', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('633', N'Huyện Chư Sê', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('634', N'Huyện Đăk Pơ', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('635', N'Huyện Ia Pa', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('637', N'Huyện Krông Pa', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('638', N'Huyện Phú Thiện', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('639', N'Huyện Chư Pưh', N'Huyện', '64');
INSERT INTO QuanHuyen VALUES ('643', N'Buôn Ma Thuột', N'Thành phố', '66');
INSERT INTO QuanHuyen VALUES ('644', N'Thị Xã Buôn Hồ', N'Thị xã', '66');
INSERT INTO QuanHuyen VALUES ('645', N'Huyện Ea H leo', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('646', N'Huyện Ea Súp', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('647', N'Huyện Buôn Đôn', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('648', N'Huyện Cư M gar', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('649', N'Huyện Krông Búk', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('650', N'Huyện Krông Năng', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('651', N'Huyện Ea Kar', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('652', N'Huyện M Đrắk', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('653', N'Huyện Krông Bông', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('654', N'Huyện Krông Pắc', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('655', N'Huyện Krông A Na', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('656', N'Huyện Lắk', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('657', N'Huyện Cư Kuin', N'Huyện', '66');
INSERT INTO QuanHuyen VALUES ('660', N'Thị xã Gia Nghĩa', N'Thị xã', '67');
INSERT INTO QuanHuyen VALUES ('661', N'Huyện Đăk Glong', N'Huyện', '67');
INSERT INTO QuanHuyen VALUES ('662', N'Huyện Cư Jút', N'Huyện', '67');
INSERT INTO QuanHuyen VALUES ('663', N'Huyện Đắk Mil', N'Huyện', '67');
INSERT INTO QuanHuyen VALUES ('664', N'Huyện Krông Nô', N'Huyện', '67');
INSERT INTO QuanHuyen VALUES ('665', N'Huyện Đắk Song', N'Huyện', '67');
INSERT INTO QuanHuyen VALUES ('666', N'Huyện Đắk R Lấp', N'Huyện', '67');
INSERT INTO QuanHuyen VALUES ('667', N'Huyện Tuy Đức', N'Huyện', '67');
INSERT INTO QuanHuyen VALUES ('672', N'Đà Lạt', N'Thành phố', '68');
INSERT INTO QuanHuyen VALUES ('673', N'Bảo Lộc', N'Thành phố', '68');
INSERT INTO QuanHuyen VALUES ('674', N'Huyện Đam Rông', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('675', N'Huyện Lạc Dương', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('676', N'Huyện Lâm Hà', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('677', N'Huyện Đơn Dương', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('678', N'Huyện Đức Trọng', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('679', N'Huyện Di Linh', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('680', N'Huyện Bảo Lâm', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('681', N'Huyện Đạ Huoai', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('682', N'Huyện Đạ Tẻh', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('683', N'Huyện Cát Tiên', N'Huyện', '68');
INSERT INTO QuanHuyen VALUES ('688', N'Thị xã Phước Long', N'Thị xã', '70');
INSERT INTO QuanHuyen VALUES ('689', N'Thị xã Đồng Xoài', N'Thị xã', '70');
INSERT INTO QuanHuyen VALUES ('690', N'Thị xã Bình Long', N'Thị xã', '70');
INSERT INTO QuanHuyen VALUES ('691', N'Huyện Bù Gia Mập', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('692', N'Huyện Lộc Ninh', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('693', N'Huyện Bù Đốp', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('694', N'Huyện Hớn Quản', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('695', N'Huyện Đồng Phú', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('696', N'Huyện Bù Đăng', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('697', N'Huyện Chơn Thành', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('698', N'Huyện Phú Riềng', N'Huyện', '70');
INSERT INTO QuanHuyen VALUES ('703', N'Tây Ninh', N'Thành phố', '72');
INSERT INTO QuanHuyen VALUES ('705', N'Huyện Tân Biên', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('706', N'Huyện Tân Châu', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('707', N'Huyện Dương Minh Châu', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('708', N'Huyện Châu Thành', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('709', N'Huyện Hòa Thành', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('710', N'Huyện Gò Dầu', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('711', N'Huyện Bến Cầu', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('712', N'Huyện Trảng Bàng', N'Huyện', '72');
INSERT INTO QuanHuyen VALUES ('718', N'Thủ Dầu Một', N'Thành phố', '74');
INSERT INTO QuanHuyen VALUES ('719', N'Huyện Bàu Bàng', N'Huyện', '74');
INSERT INTO QuanHuyen VALUES ('720', N'Huyện Dầu Tiếng', N'Huyện', '74');
INSERT INTO QuanHuyen VALUES ('721', N'Thị xã Bến Cát', N'Thị xã', '74');
INSERT INTO QuanHuyen VALUES ('722', N'Huyện Phú Giáo', N'Huyện', '74');
INSERT INTO QuanHuyen VALUES ('723', N'Thị xã Tân Uyên', N'Thị xã', '74');
INSERT INTO QuanHuyen VALUES ('724', N'Thị xã Dĩ An', N'Thị xã', '74');
INSERT INTO QuanHuyen VALUES ('725', N'Thị xã Thuận An', N'Thị xã', '74');
INSERT INTO QuanHuyen VALUES ('726', N'Huyện Bắc Tân Uyên', N'Huyện', '74');
INSERT INTO QuanHuyen VALUES ('731', N'Biên Hòa', N'Thành phố', '75');
INSERT INTO QuanHuyen VALUES ('732', N'Thị xã Long Khánh', N'Thị xã', '75');
INSERT INTO QuanHuyen VALUES ('734', N'Huyện Tân Phú', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('735', N'Huyện Vĩnh Cửu', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('736', N'Huyện Định Quán', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('737', N'Huyện Trảng Bom', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('738', N'Huyện Thống Nhất', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('739', N'Huyện Cẩm Mỹ', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('740', N'Huyện Long Thành', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('741', N'Huyện Xuân Lộc', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('742', N'Huyện Nhơn Trạch', N'Huyện', '75');
INSERT INTO QuanHuyen VALUES ('747', N'Vũng Tàu', N'Thành phố', '77');
INSERT INTO QuanHuyen VALUES ('748', N'Bà Rịa', N'Thành phố', '77');
INSERT INTO QuanHuyen VALUES ('750', N'Huyện Châu Đức', N'Huyện', '77');
INSERT INTO QuanHuyen VALUES ('751', N'Huyện Xuyên Mộc', N'Huyện', '77');
INSERT INTO QuanHuyen VALUES ('752', N'Huyện Long Điền', N'Huyện', '77');
INSERT INTO QuanHuyen VALUES ('753', N'Huyện Đất Đỏ', N'Huyện', '77');
INSERT INTO QuanHuyen VALUES ('754', N'Huyện Tân Thành', N'Huyện', '77');
INSERT INTO QuanHuyen VALUES ('755', N'Huyện Côn Đảo', N'Huyện', '77');
INSERT INTO QuanHuyen VALUES ('760', N'Quận 1', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('761', N'Quận 12', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('762', N'Quận Thủ Đức', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('763', N'Quận 9', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('764', N'Quận Gò Vấp', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('765', N'Quận Bình Thạnh', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('766', N'Quận Tân Bình', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('767', N'Quận Tân Phú', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('768', N'Quận Phú Nhuận', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('769', N'Quận 2', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('770', N'Quận 3', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('771', N'Quận 10', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('772', N'Quận 11', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('773', N'Quận 4', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('774', N'Quận 5', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('775', N'Quận 6', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('776', N'Quận 8', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('777', N'Quận Bình Tân', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('778', N'Quận 7', N'Quận', '79');
INSERT INTO QuanHuyen VALUES ('783', N'Huyện Củ Chi', N'Huyện', '79');
INSERT INTO QuanHuyen VALUES ('784', N'Huyện Hóc Môn', N'Huyện', '79');
INSERT INTO QuanHuyen VALUES ('785', N'Huyện Bình Chánh', N'Huyện', '79');
INSERT INTO QuanHuyen VALUES ('786', N'Huyện Nhà Bè', N'Huyện', '79');
INSERT INTO QuanHuyen VALUES ('787', N'Huyện Cần Giờ', N'Huyện', '79');
INSERT INTO QuanHuyen VALUES ('794', N'Tân An', N'Thành phố', '80');
INSERT INTO QuanHuyen VALUES ('795', N'Thị xã Kiến Tường', N'Thị xã', '80');
INSERT INTO QuanHuyen VALUES ('796', N'Huyện Tân Hưng', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('797', N'Huyện Vĩnh Hưng', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('798', N'Huyện Mộc Hóa', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('799', N'Huyện Tân Thạnh', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('800', N'Huyện Thạnh Hóa', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('801', N'Huyện Đức Huệ', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('802', N'Huyện Đức Hòa', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('803', N'Huyện Bến Lức', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('804', N'Huyện Thủ Thừa', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('805', N'Huyện Tân Trụ', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('806', N'Huyện Cần Đước', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('807', N'Huyện Cần Giuộc', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('808', N'Huyện Châu Thành', N'Huyện', '80');
INSERT INTO QuanHuyen VALUES ('815', N'Mỹ Tho', N'Thành phố', '82');
INSERT INTO QuanHuyen VALUES ('816', N'Thị xã Gò Công', N'Thị xã', '82');
INSERT INTO QuanHuyen VALUES ('817', N'Thị xã Cai Lậy', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('818', N'Huyện Tân Phước', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('819', N'Huyện Cái Bè', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('820', N'Huyện Cai Lậy', N'Thị xã', '82');
INSERT INTO QuanHuyen VALUES ('821', N'Huyện Châu Thành', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('822', N'Huyện Chợ Gạo', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('823', N'Huyện Gò Công Tây', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('824', N'Huyện Gò Công Đông', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('825', N'Huyện Tân Phú Đông', N'Huyện', '82');
INSERT INTO QuanHuyen VALUES ('829', N'Bến Tre', N'Thành phố', '83');
INSERT INTO QuanHuyen VALUES ('831', N'Huyện Châu Thành', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('832', N'Huyện Chợ Lách', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('833', N'Huyện Mỏ Cày Nam', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('834', N'Huyện Giồng Trôm', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('835', N'Huyện Bình Đại', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('836', N'Huyện Ba Tri', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('837', N'Huyện Thạnh Phú', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('838', N'Huyện Mỏ Cày Bắc', N'Huyện', '83');
INSERT INTO QuanHuyen VALUES ('842', N'Trà Vinh', N'Thành phố', '84');
INSERT INTO QuanHuyen VALUES ('844', N'Huyện Càng Long', N'Huyện', '84');
INSERT INTO QuanHuyen VALUES ('845', N'Huyện Cầu Kè', N'Huyện', '84');
INSERT INTO QuanHuyen VALUES ('846', N'Huyện Tiểu Cần', N'Huyện', '84');
INSERT INTO QuanHuyen VALUES ('847', N'Huyện Châu Thành', N'Huyện', '84');
INSERT INTO QuanHuyen VALUES ('848', N'Huyện Cầu Ngang', N'Huyện', '84');
INSERT INTO QuanHuyen VALUES ('849', N'Huyện Trà Cú', N'Huyện', '84');
INSERT INTO QuanHuyen VALUES ('850', N'Huyện Duyên Hải', N'Huyện', '84');
INSERT INTO QuanHuyen VALUES ('851', N'Thị xã Duyên Hải', N'Thị xã', '84');
INSERT INTO QuanHuyen VALUES ('855', N'Vĩnh Long', N'Thành phố', '86');
INSERT INTO QuanHuyen VALUES ('857', N'Huyện Long Hồ', N'Huyện', '86');
INSERT INTO QuanHuyen VALUES ('858', N'Huyện Mang Thít', N'Huyện', '86');
INSERT INTO QuanHuyen VALUES ('859', N'Huyện  Vũng Liêm', N'Huyện', '86');
INSERT INTO QuanHuyen VALUES ('860', N'Huyện Tam Bình', N'Huyện', '86');
INSERT INTO QuanHuyen VALUES ('861', N'Thị xã Bình Minh', N'Thị xã', '86');
INSERT INTO QuanHuyen VALUES ('862', N'Huyện Trà Ôn', N'Huyện', '86');
INSERT INTO QuanHuyen VALUES ('863', N'Huyện Bình Tân', N'Huyện', '86');
INSERT INTO QuanHuyen VALUES ('866', N'Cao Lãnh', N'Thành phố', '87');
INSERT INTO QuanHuyen VALUES ('867', N'Sa Đéc', N'Thành phố', '87');
INSERT INTO QuanHuyen VALUES ('868', N'Thị xã Hồng Ngự', N'Thị xã', '87');
INSERT INTO QuanHuyen VALUES ('869', N'Huyện Tân Hồng', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('870', N'Huyện Hồng Ngự', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('871', N'Huyện Tam Nông', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('872', N'Huyện Tháp Mười', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('873', N'Huyện Cao Lãnh', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('874', N'Huyện Thanh Bình', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('875', N'Huyện Lấp Vò', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('876', N'Huyện Lai Vung', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('877', N'Huyện Châu Thành', N'Huyện', '87');
INSERT INTO QuanHuyen VALUES ('883', N'Long Xuyên', N'Thành phố', '89');
INSERT INTO QuanHuyen VALUES ('884', N'Châu Đốc', N'Thành phố', '89');
INSERT INTO QuanHuyen VALUES ('886', N'Huyện An Phú', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('887', N'Thị xã Tân Châu', N'Thị xã', '89');
INSERT INTO QuanHuyen VALUES ('888', N'Huyện Phú Tân', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('889', N'Huyện Châu Phú', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('890', N'Huyện Tịnh Biên', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('891', N'Huyện Tri Tôn', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('892', N'Huyện Châu Thành', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('893', N'Huyện Chợ Mới', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('894', N'Huyện Thoại Sơn', N'Huyện', '89');
INSERT INTO QuanHuyen VALUES ('899', N'Rạch Giá', N'Thành phố', '91');
INSERT INTO QuanHuyen VALUES ('900', N'Thị xã Hà Tiên', N'Thị xã', '91');
INSERT INTO QuanHuyen VALUES ('902', N'Huyện Kiên Lương', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('903', N'Huyện Hòn Đất', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('904', N'Huyện Tân Hiệp', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('905', N'Huyện Châu Thành', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('906', N'Huyện Giồng Riềng', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('907', N'Huyện Gò Quao', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('908', N'Huyện An Biên', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('909', N'Huyện An Minh', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('910', N'Huyện Vĩnh Thuận', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('911', N'Huyện Phú Quốc', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('912', N'Huyện Kiên Hải', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('913', N'Huyện U Minh Thượng', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('914', N'Huyện Giang Thành', N'Huyện', '91');
INSERT INTO QuanHuyen VALUES ('916', N'Quận Ninh Kiều', N'Quận', '92');
INSERT INTO QuanHuyen VALUES ('917', N'Quận Ô Môn', N'Quận', '92');
INSERT INTO QuanHuyen VALUES ('918', N'Quận Bình Thuỷ', N'Quận', '92');
INSERT INTO QuanHuyen VALUES ('919', N'Quận Cái Răng', N'Quận', '92');
INSERT INTO QuanHuyen VALUES ('923', N'Quận Thốt Nốt', N'Quận', '92');
INSERT INTO QuanHuyen VALUES ('924', N'Huyện Vĩnh Thạnh', N'Huyện', '92');
INSERT INTO QuanHuyen VALUES ('925', N'Huyện Cờ Đỏ', N'Huyện', '92');
INSERT INTO QuanHuyen VALUES ('926', N'Huyện Phong Điền', N'Huyện', '92');
INSERT INTO QuanHuyen VALUES ('927', N'Huyện Thới Lai', N'Huyện', '92');
INSERT INTO QuanHuyen VALUES ('930', N'Vị Thanh', N'Thành phố', '93');
INSERT INTO QuanHuyen VALUES ('931', N'Thị xã Ngã Bảy', N'Thị xã', '93');
INSERT INTO QuanHuyen VALUES ('932', N'Huyện Châu Thành A', N'Huyện', '93');
INSERT INTO QuanHuyen VALUES ('933', N'Huyện Châu Thành', N'Huyện', '93');
INSERT INTO QuanHuyen VALUES ('934', N'Huyện Phụng Hiệp', N'Huyện', '93');
INSERT INTO QuanHuyen VALUES ('935', N'Huyện Vị Thuỷ', N'Huyện', '93');
INSERT INTO QuanHuyen VALUES ('936', N'Huyện Long Mỹ', N'Huyện', '93');
INSERT INTO QuanHuyen VALUES ('937', N'Thị xã Long Mỹ', N'Thị xã', '93');
INSERT INTO QuanHuyen VALUES ('941', N'Sóc Trăng', N'Thành phố', '94');
INSERT INTO QuanHuyen VALUES ('942', N'Huyện Châu Thành', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('943', N'Huyện Kế Sách', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('944', N'Huyện Mỹ Tú', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('945', N'Huyện Cù Lao Dung', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('946', N'Huyện Long Phú', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('947', N'Huyện Mỹ Xuyên', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('948', N'Thị xã Ngã Năm', N'Thị xã', '94');
INSERT INTO QuanHuyen VALUES ('949', N'Huyện Thạnh Trị', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('950', N'Thị xã Vĩnh Châu', N'Thị xã', '94');
INSERT INTO QuanHuyen VALUES ('951', N'Huyện Trần Đề', N'Huyện', '94');
INSERT INTO QuanHuyen VALUES ('954', N'Bạc Liêu', N'Thành phố', '95');
INSERT INTO QuanHuyen VALUES ('956', N'Huyện Hồng Dân', N'Huyện', '95');
INSERT INTO QuanHuyen VALUES ('957', N'Huyện Phước Long', N'Huyện', '95');
INSERT INTO QuanHuyen VALUES ('958', N'Huyện Vĩnh Lợi', N'Huyện', '95');
INSERT INTO QuanHuyen VALUES ('959', N'Thị xã Giá Rai', N'Thị xã', '95');
INSERT INTO QuanHuyen VALUES ('960', N'Huyện Đông Hải', N'Huyện', '95');
INSERT INTO QuanHuyen VALUES ('961', N'Huyện Hoà Bình', N'Huyện', '95');
INSERT INTO QuanHuyen VALUES ('964', N'Cà Mau', N'Thành phố', '96');
INSERT INTO QuanHuyen VALUES ('966', N'Huyện U Minh', N'Huyện', '96');
INSERT INTO QuanHuyen VALUES ('967', N'Huyện Thới Bình', N'Huyện', '96');
INSERT INTO QuanHuyen VALUES ('968', N'Huyện Trần Văn Thời', N'Huyện', '96');
INSERT INTO QuanHuyen VALUES ('969', N'Huyện Cái Nước', N'Huyện', '96');
INSERT INTO QuanHuyen VALUES ('970', N'Huyện Đầm Dơi', N'Huyện', '96');
INSERT INTO QuanHuyen VALUES ('971', N'Huyện Năm Căn', N'Huyện', '96');
INSERT INTO QuanHuyen VALUES ('972', N'Huyện Phú Tân', N'Huyện', '96');
INSERT INTO QuanHuyen VALUES ('973', N'Huyện Ngọc Hiển', N'Huyện', '96');
